name: CI Pipeline # Name of the pipeline

# Trigger: Runs whenever you push to any branch (won't happen locally yet)
on: [push]

# Jobs to run
jobs:
  test: # Job name
    runs-on: ubuntu-latest # Runs on an Ubuntu virtual machine
    steps:
      # Step 1: Check out your code
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js (matches your Dockerfile's node:18.20.7)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run your tests
      - name: Run tests
        run: npm test